- name: Delete the user ansible
  lineinfile:
    path: /etc/sudoers
    state: absent
    regexp: "{{ item }}"
  with_items:
    - 'ansible'
    - '%ansible'
  tags:
  - delete-user

- name: Create the user ansible
  user:
    name: ansible
    update_password: always
    shell: /bin/bash
    password: "{{ user_password_1 | password_hash('sha512') }}"
  tags:
  - create-user

- name: Add user ansible to sudoers file
  lineinfile:
    path: /etc/sudoers
    regexp: '^%ansible\s'
    state: present
#    line: '%ansible  ALL=(ALL)       NOPASSWD:ALL'
    line: '%ansible  ALL=(ALL)       ALL'
  tags:
  - add-user-sudoers-file

- name: Creates directory include file authorized keys for user ansible
  file:
    path: /home/ansible/.ssh
    state: directory
    owner: ansible
    group: ansible
    mode: 0700
  tags:
  - add-user-sudoers-file

- name: Create file authorized keys for user ansible
  file:
    path: /home/ansible/.ssh/authorized_keys
    state: touch
    owner: ansible
    group: ansible
    mode: 0644
  tags:
  - create-file-authorized

- name: Deploy public key of user ansible
  template:
    src: authorized_keys
    dest: /home/ansible/.ssh/authorized_keys
  tags:
  - deploy-file-authorized

- name: Change file ownership, group and permissions file authorized_keys of user ansible
  file:
    path: /home/ansible/.ssh/authorized_keys
    owner: ansible
    group: ansible
    mode: '0644'
  tags:
  - change-permissions-file-authorized
